In [ ]:
#pip install numpy

In [1]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
print("Numpy successfully imported")

Numpy successfully imported


In [ ]:
lst=list(range(1,25))
''

<class 'numpy.ndarray'>
<class 'type'>


In [16]:
lst

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24]

In [39]:
arr1=np.array(list)
arr1

array(['113', 'Hello', '2.35', 'True'], dtype='<U32')

In [40]:
print(type(arr1))
print(type(list))

<class 'numpy.ndarray'>
<class 'list'>


In [41]:
#creating numpy array
arr2=np.array([1,2,3,4])

In [42]:
print(arr2)

[1 2 3 4]


In [29]:
list1 = [113,'Hello',2.35,True]

In [30]:
print(list1)

[113, 'Hello', 2.35, True]


In [37]:
#arange() - used to create the array
arr3 = np.arange(1,25)
print(arr3) #single dimesional array

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [44]:
# creating 2d array
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 2d array zero
arr = np.zeros([3,4]) # creating a 2d array using zeros(())
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Linespace() used to create array in the equal intervals
arr = np.linspace(1,10,5).reshape(5,1)
arr

array([[ 1.  ],
       [ 3.25],
       [ 5.5 ],
       [ 7.75],
       [10.  ]])

In [47]:
# 3d array
arr = np.array([[[1,2,3,5],[4,5,6,8],[7,8,9,10]],[[4,56,25,85],[42,21,65,85],[12,53,86,21]]])
arr

array([[[ 1,  2,  3,  5],
        [ 4,  5,  6,  8],
        [ 7,  8,  9, 10]],

       [[ 4, 56, 25, 85],
        [42, 21, 65, 85],
        [12, 53, 86, 21]]])

In [53]:
# Reshaping 1d to 2d with reshape()
arr = np.arange(0,30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
# Random initialization
arr = np.random.randint(1,5,9)  # generates 9 random numbers b/w 1 to 5
arr

array([3, 2, 3, 2, 2, 1, 4, 4, 1])

In [ ]:
arr = np.random.randint(1,5,(3,3)) # generate3x3 amtrix b/w 1 to 5
arr

array([[2, 4, 2],
       [3, 1, 4],
       [2, 4, 1]])

In [57]:
arr = np.random.randint(1,5,(3,3,3)) # generate3x3 amtrix b/w 1 to 5
arr

array([[[2, 3, 2],
        [4, 1, 2],
        [3, 3, 4]],

       [[3, 1, 1],
        [3, 4, 4],
        [4, 1, 4]],

       [[3, 2, 3],
        [4, 1, 4],
        [2, 4, 3]]])

In [59]:
arr = np.random.random(10) # Random arrays of 10 to b/w 0 to 10
arr

array([0.9341479 , 0.70536686, 0.37929953, 0.10180541, 0.02189639,
       0.69774394, 0.480604  , 0.7335528 , 0.98648985, 0.72845543])

In [61]:
arr = np.random.randint((10,10))
arr

array([1, 7])

In [63]:
arr.dtpe

AttributeError: 'numpy.ndarray' object has no attribute 'dtpe'

In [74]:
arr = np.arange(60).reshape(10,6)
print(arr)
arr.dtype

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]
 [48 49 50 51 52 53]
 [54 55 56 57 58 59]]


dtype('int32')

In [ ]:
print(arr.ndim)  # dimesion of array
print(arr.size) # Total elements in array
print(arr.shape) # (row , columns) in array

2
60
(10, 6)


In [64]:
arr = np.random.random((10,10))
arr

array([[0.1327257 , 0.06832753, 0.15505335, 0.77332574, 0.46881753,
        0.6850053 , 0.17152076, 0.18923654, 0.82720811, 0.85638017],
       [0.2209153 , 0.25958908, 0.22448826, 0.09934217, 0.03582143,
        0.37648379, 0.71075567, 0.05681093, 0.47967364, 0.52705095],
       [0.3491384 , 0.21200446, 0.24651649, 0.68688834, 0.76138514,
        0.58159053, 0.57349447, 0.15363089, 0.82165465, 0.54675364],
       [0.53810782, 0.89189195, 0.28127193, 0.40273702, 0.01704215,
        0.98870831, 0.78375994, 0.33103716, 0.83327684, 0.10088458],
       [0.41289521, 0.48843949, 0.20577029, 0.49425939, 0.37439965,
        0.99756181, 0.1428454 , 0.66950666, 0.17186575, 0.76959724],
       [0.2746789 , 0.37245092, 0.99803245, 0.04894151, 0.88389426,
        0.94761921, 0.02075664, 0.68822597, 0.59276005, 0.28000246],
       [0.39429474, 0.79918083, 0.39530899, 0.44573497, 0.66427046,
        0.73076145, 0.24856681, 0.15971087, 0.43556824, 0.08130383],
       [0.8484639 , 0.39090783, 0.6549377

In [76]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [78]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [87]:
lst = [[1,2,3],[4,5,6]]
arr = np.array(list)
arr

array(['113', 'Hello', '2.35', 'True'], dtype='<U32')

In [ ]:
arr.T.shape # reverse the shape of array

(4,)

In [86]:
arr.T

array(['113', 'Hello', '2.35', 'True'], dtype='<U32')

In [88]:
arr

array(['113', 'Hello', '2.35', 'True'], dtype='<U32')