In [87]:
#pip install numpy

In [88]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [89]:
import numpy as np
print("Numpy successfully imported")

Numpy successfully imported


In [90]:
lst=list(range(1,25))
''

''

In [91]:
lst

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24]

In [92]:
arr1=np.array(list)
arr1

array(<class 'list'>, dtype=object)

In [93]:
print(type(arr1))
print(type(list))

<class 'numpy.ndarray'>
<class 'type'>


In [94]:
#creating numpy array
arr2=np.array([1,2,3,4])

In [95]:
print(arr2)

[1 2 3 4]


In [96]:
list1 = [113,'Hello',2.35,True]

In [97]:
print(list1)

[113, 'Hello', 2.35, True]


In [98]:
#arange() - used to create the array
arr3 = np.arange(1,25)
print(arr3) #single dimesional array

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [99]:
# creating 2d array
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
# 2d array zero
arr = np.zeros([3,4]) # creating a 2d array using zeros(())
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [101]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [102]:
# Linespace() used to create array in the equal intervals
arr = np.linspace(1,10,5).reshape(5,1)
arr

array([[ 1.  ],
       [ 3.25],
       [ 5.5 ],
       [ 7.75],
       [10.  ]])

In [103]:
# 3d array
arr = np.array([[[1,2,3,5],[4,5,6,8],[7,8,9,10]],[[4,56,25,85],[42,21,65,85],[12,53,86,21]]])
arr

array([[[ 1,  2,  3,  5],
        [ 4,  5,  6,  8],
        [ 7,  8,  9, 10]],

       [[ 4, 56, 25, 85],
        [42, 21, 65, 85],
        [12, 53, 86, 21]]])

In [104]:
# Reshaping 1d to 2d with reshape()
arr = np.arange(0,30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [105]:
# Random initialization
arr = np.random.randint(1,5,9)  # generates 9 random numbers b/w 1 to 5
arr

array([4, 3, 1, 2, 2, 2, 2, 1, 2])

In [106]:
arr = np.random.randint(1,5,(3,3)) # generate3x3 amtrix b/w 1 to 5
arr

array([[3, 1, 4],
       [1, 4, 2],
       [3, 3, 1]])

In [107]:
arr = np.random.randint(1,5,(3,3,3)) # generate3x3 amtrix b/w 1 to 5
arr

array([[[3, 2, 2],
        [2, 2, 4],
        [2, 3, 2]],

       [[1, 2, 1],
        [4, 4, 3],
        [2, 3, 2]],

       [[3, 2, 4],
        [3, 1, 1],
        [3, 1, 3]]])

In [108]:
arr = np.random.random(10) # Random arrays of 10 to b/w 0 to 10
arr

array([0.96981493, 0.39087586, 0.94533769, 0.45810916, 0.15928582,
       0.98989512, 0.21871857, 0.38992658, 0.7989251 , 0.29700143])

In [109]:
arr = np.random.randint((10,10))
arr

array([8, 6])

In [110]:
arr.dtpe

AttributeError: 'numpy.ndarray' object has no attribute 'dtpe'

In [ ]:
arr = np.arange(60).reshape(10,6)
print(arr)
arr.dtype

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]
 [48 49 50 51 52 53]
 [54 55 56 57 58 59]]


dtype('int32')

In [ ]:
print(arr.ndim)  # dimesion of array
print(arr.size) # Total elements in array
print(arr.shape) # (row , columns) in array

2
60
(10, 6)


In [ ]:
arr = np.random.random((10,10))
arr

array([[0.1327257 , 0.06832753, 0.15505335, 0.77332574, 0.46881753,
        0.6850053 , 0.17152076, 0.18923654, 0.82720811, 0.85638017],
       [0.2209153 , 0.25958908, 0.22448826, 0.09934217, 0.03582143,
        0.37648379, 0.71075567, 0.05681093, 0.47967364, 0.52705095],
       [0.3491384 , 0.21200446, 0.24651649, 0.68688834, 0.76138514,
        0.58159053, 0.57349447, 0.15363089, 0.82165465, 0.54675364],
       [0.53810782, 0.89189195, 0.28127193, 0.40273702, 0.01704215,
        0.98870831, 0.78375994, 0.33103716, 0.83327684, 0.10088458],
       [0.41289521, 0.48843949, 0.20577029, 0.49425939, 0.37439965,
        0.99756181, 0.1428454 , 0.66950666, 0.17186575, 0.76959724],
       [0.2746789 , 0.37245092, 0.99803245, 0.04894151, 0.88389426,
        0.94761921, 0.02075664, 0.68822597, 0.59276005, 0.28000246],
       [0.39429474, 0.79918083, 0.39530899, 0.44573497, 0.66427046,
        0.73076145, 0.24856681, 0.15971087, 0.43556824, 0.08130383],
       [0.8484639 , 0.39090783, 0.6549377

In [ ]:
arr.flatten() # 2D to 1D array conversion

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
lst = [[1,2,3],[4,5,6]]
arr = np.array(list)
arr

array(['113', 'Hello', '2.35', 'True'], dtype='<U32')

In [ ]:
arr.T.shape # reverse the shape of array

(4,)

In [ ]:
arr.T

array(['113', 'Hello', '2.35', 'True'], dtype='<U32')

In [ ]:
arr

array(['113', 'Hello', '2.35', 'True'], dtype='<U32')

In [ ]:
arr=np.array([1,64,23,34,56,76,54,33,98,76])
arr

array([ 1, 64, 23, 34, 56, 76, 54, 33, 98, 76])

In [ ]:
arr[3:11]

array([34, 56, 76, 54, 33, 98, 76])

In [ ]:
lst = list(range(1,100))
arr = np.array(lst)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
arr[5:60]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
       57, 58, 59, 60])

In [ ]:
arr[0:22:2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [ ]:
arr=arr.reshape(33,3)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
arr[0:5,1:2]

array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14]])

In [ ]:
arr[2,2] # particluar element find form matrix

9

In [ ]:
arr[-1][-1] # array ka last element print hoge

99

In [ ]:
arr[:4][-1]

array([10, 11, 12])

In [ ]:
arr[3,1] = 123
arr

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [ 10, 123,  12],
       [ 13,  14,  15],
       [ 16,  17,  18],
       [ 19,  20,  21],
       [ 22,  23,  24],
       [ 25,  26,  27],
       [ 28,  29,  30],
       [ 31,  32,  33],
       [ 34,  35,  36],
       [ 37,  38,  39],
       [ 40,  41,  42],
       [ 43,  44,  45],
       [ 46,  47,  48],
       [ 49,  50,  51],
       [ 52,  53,  54],
       [ 55,  56,  57],
       [ 58,  59,  60],
       [ 61,  62,  63],
       [ 64,  65,  66],
       [ 67,  68,  69],
       [ 70,  71,  72],
       [ 73,  74,  75],
       [ 76,  77,  78],
       [ 79,  80,  81],
       [ 82,  83,  84],
       [ 85,  86,  87],
       [ 88,  89,  90],
       [ 91,  92,  93],
       [ 94,  95,  96],
       [ 97,  98,  99]])

In [ ]:
arr=np.arange(0,30).reshape(3,5,2)

In [ ]:
arr[0][2:7]

array([[4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
arr[:,0:1,0:1]

array([[[ 0]],

       [[10]],

       [[20]]])

In [ ]:
arr=np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
arr +2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61])

In [ ]:
arr *2

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118])

In [ ]:
arr -2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
       15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55, 56, 57])

In [ ]:
arr /2

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5])

In [ ]:
arr=arr.reshape(12,5)

In [ ]:
arr1=np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
arr = arr1.reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [ ]:
x=list(range(0,5))
y=list(range(3,8))

print(x)
print(y)

print(x+y)

[0, 1, 2, 3, 4]
[3, 4, 5, 6, 7]
[0, 1, 2, 3, 4, 3, 4, 5, 6, 7]


In [ ]:
arr1 = np.array(x)
arr2 = np.array(y)

print(arr1)
print(arr2)
# print(arr1 + arr2)

[0 1 2 3 4]
[3 4 5 6 7]


In [ ]:
arr1 + arr2

array([ 3,  5,  7,  9, 11])

In [ ]:
print(x*y)

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
arr1 * arr2

array([ 0,  4, 10, 18, 28])