In [3]:
import numpy as np

In [1]:
lst = [1,23,54,32]

In [4]:
arr=np.array(lst)

In [5]:
arr

array([ 1, 23, 54, 32])

In [7]:
#np.arange()

In [9]:
lst = list(range(1,25))
lst

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24]

In [10]:
len(lst)

24

In [11]:
arr

array([ 1, 23, 54, 32])

In [18]:
arr=np.zeros((2,3))

In [19]:
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
arr=np.ones(10)

In [16]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
arr=np.linspace(1,10,5)

In [22]:
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [24]:
arr=np.arange(0,30)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [26]:
arr.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [27]:
arr=np.random.randint(1,5,9)

In [28]:
arr

array([1, 3, 4, 2, 3, 1, 1, 2, 1])

In [31]:
arr=np.random.randint(1,5,(3,3))
arr

array([[4, 2, 4],
       [4, 4, 1],
       [2, 2, 1]])

In [34]:
arr=np.random.random(10)
arr

array([0.228098  , 0.98368645, 0.73187836, 0.47687351, 0.41390342,
       0.61140479, 0.77665495, 0.22057418, 0.01146109, 0.71051598])

In [36]:
arr=np.random.random((3,3))
arr

array([[0.62381344, 0.57017295, 0.15193649],
       [0.31064719, 0.45625056, 0.79363076],
       [0.45146549, 0.07566375, 0.69691458]])

In [37]:
arr.shape

(3, 3)

In [38]:
arr.dtype

dtype('float64')

In [39]:
arr.size

9

In [40]:
arr.ndim

2

In [42]:
arr.flatten() # 2d to 1D array conversion

array([0.62381344, 0.57017295, 0.15193649, 0.31064719, 0.45625056,
       0.79363076, 0.45146549, 0.07566375, 0.69691458])

In [43]:
list_2d = [[1,2,3],[4,5,6],[7,8,9]]

In [44]:
list_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [45]:
arr=np.array(list_2d)

In [46]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr.shape

(3, 3)

In [ ]:
n